---
- name: Create a special file
  hosts: localhost
  connection: local
  gather_facts: no

  vars:
    file_content: "Success! You done did an Ansible!"
    file_path: "/tmp/challenge_dir/"
    file_name: "challenge_file.txt"

  roles:
    - myrole
